resources:
  - name: prop1
    type: PropertyBag
    configuration:
      key1: value1
      key2: value2
  - name: git
    type: GitRepo
    configuration:
      gitProvider: TestIntegration
      path: aarvyved/runpoptest
  - name: git_IN
    type: GitRepo
    configuration:
      gitProvider: TestIntegration
      path: aarvyved/runpoptest
  - name: git_SANDWICH
    type: GitRepo
    configuration:
      gitProvider: TestIntegration
      path: aarvyved/runpoptest
pipelines: 
  - name: TRIGGER
    steps:
      - name: TRIGGER
        type: Bash
        configuration:
          outputResources:
            - name: prop1
        execution:
          onExecute:
            - write_output prop1 runId=$run_number
  - name: TRIGGER_OUT_1
    steps:
      - name: TRIGGER_OUT_1
        type: Bash
        configuration:
          inputResources:
            - name: prop1
        execution:
          onExecute:
            - printenv
  - name: TRIGGER_OUT_2
    steps:
      - name: TRIGGER_OUT_2
        type: Bash
        configuration:
          inputResources:
            - name: prop1
        execution:
          onExecute:
            - printenv
  - name: IN
    steps:
      - name: IN_TEST
        type: Bash
        configuration:
          outputResources:
            - name: git
            - name: git_SANDWICH
          inputResources:
            - name: git_IN
        execution:
            onExecute:
              - sleep 10
              - echo "done"
      - name: IN_TEST_OUT
        type: Bash
        configuration:
          inputResources:
            - name: git_SANDWICH
              trigger: false
          inputSteps:
            - name: IN_TEST
        execution:
          onExecute:
            - sleep 10
            - echo "done"
      - name: trigger_1
        type: Bash
        configuration:
          affinityGroup: trigger
          priority: 0
        execution:
          onExecute:
            - sleep 60
            - echo "done"
      - name: trigger_2
        type: Bash
        configuration:
          inputSteps:
            - name: trigger_1
        execution:
          onExecute:
            - sleep 60
            - echo "done"
      - name: trigger_3
        type: Bash
        configuration:
          inputSteps:
            - name: trigger_2
        execution:
          onExecute:
            - sleep 60
            - echo "done"
